# Generated by Django 4.1.4 on 2023-01-02 15:32

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[src.base.services.size_validator, django.core.validators.FileExtensionValidator(allowed_extensions=('jpg',))], verbose_name='Изображение'),
        ),
    ]
